# Generated by Django 5.2.6 on 2025-09-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_advisor_adhar_number_advisor_age_advisor_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='education',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='advisor',
            old_name='photo',
            new_name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='adhar_number',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='username',
        ),
        migrations.AddField(
            model_name='advisor',
            name='advisor_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='confirm_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advisor',
            name='country_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='educational_certificate',
            field=models.FileField(blank=True, null=True, upload_to='advisor_certificates/'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='govt_id_file',
            field=models.FileField(blank=True, null=True, upload_to='advisor_ids/'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='govt_id_proof_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='govt_id_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='language_preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='previous_companies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='advisor_resumes/'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='specialized_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='state_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
