# Generated by Django 5.2.6 on 2025-10-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_rename_education_advisor_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, unique=True)),
                ('is_available', models.BooleanField(default=False)),
                ('total_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('time_range', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='advisor.advisor')),
            ],
            options={
                'unique_together': {('advisor', 'day')},
            },
        ),
    ]
