# Generated by Django 5.2.6 on 2025-11-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_advisoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
