# Generated by Django 5.2.6 on 2025-11-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0005_advisor_consultation_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='age',
            new_name='dob_year',
        ),
    ]
