# Generated by Django 5.2.6 on 2025-11-06 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_rename_age_advisor_dob_year_advisorrating'),
        ('user', '0003_appointment_is_attended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advisorrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='advisorrating',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='user.appointment'),
        ),
        migrations.RemoveField(
            model_name='advisorrating',
            name='review',
        ),
        migrations.CreateModel(
            name='AdvisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='advisor.advisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('advisor', 'user')},
            },
        ),
    ]
