# Generated by Django 5.2.6 on 2025-11-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0007_alter_advisorrating_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisoravailability',
            name='total_slots',
        ),
    ]
