# Generated by Django 5.2.6 on 2025-10-07 07:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisor', '0003_rename_education_advisor_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='advisor_photos/')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(65)])),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country_address', models.CharField(blank=True, max_length=255, null=True)),
                ('state_address', models.CharField(blank=True, max_length=255, null=True)),
                ('language_preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('advisor_type', models.CharField(blank=True, choices=[('financial', 'Financial Advisor'), ('lifestyle', 'Lifestyle Advisor'), ('legal', 'Legal Advisor'), ('healthcare', 'Healthcare Advisor'), ('travel', 'Travel Advisor'), ('automobile', 'Automobile Advisor'), ('architectural', 'Architectural Advisor')], max_length=50, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('highest_qualification', models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('degree', 'Degree')], max_length=20, null=True)),
                ('specialized_in', models.CharField(blank=True, max_length=255, null=True)),
                ('educational_certificate', models.FileField(blank=True, null=True, upload_to='advisor_certificates/')),
                ('previous_companies', models.TextField(blank=True, help_text='List of companies and roles', null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='advisor_resumes/')),
                ('govt_id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('aadhar', 'Aadhar'), ('license', 'License')], max_length=20, null=True)),
                ('govt_id_proof_id', models.CharField(blank=True, max_length=30, null=True)),
                ('govt_id_file', models.FileField(blank=True, null=True, upload_to='advisor_ids/')),
                ('confirm_details', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('preferred_day', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('communication_method', models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('whatsapp', 'WhatsApp Video Call'), ('zoom', 'Zoom'), ('phone', 'Phone Call')], max_length=20, null=True)),
                ('decline_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='advisor.advisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('interests', models.TextField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('retirement_planning_age', models.PositiveIntegerField(blank=True, null=True)),
                ('current_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_savings_at_retirement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('post_retirement_travel', models.BooleanField(default=False)),
                ('post_retirement_hobbies', models.BooleanField(default=False)),
                ('post_retirement_family_together', models.BooleanField(default=False)),
                ('post_retirement_social_work', models.BooleanField(default=False)),
                ('post_retirement_garage', models.BooleanField(default=False)),
                ('post_retirement_luxury_life', models.BooleanField(default=False)),
                ('retirement_location_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('dream_type', models.CharField(blank=True, choices=[('Pre Retirement', 'Pre Retirement'), ('Post Retirement', 'Post Retirement')], max_length=50, null=True)),
                ('top_dream_1', models.CharField(blank=True, max_length=255, null=True)),
                ('top_dream_2', models.CharField(blank=True, max_length=255, null=True)),
                ('top_dream_3', models.CharField(blank=True, max_length=255, null=True)),
                ('top_dream_priorities', models.TextField(blank=True, null=True)),
                ('dream_description', models.TextField(blank=True, null=True)),
                ('initial_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
