# Generated by Django 5.2.6 on 2025-11-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorrequest',
            name='age',
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='dob_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
