# Generated by Django 5.2.6 on 2025-10-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='communication_method',
            field=models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('whatsapp video call', 'WhatsApp Video Call'), ('zoom', 'Zoom'), ('phone', 'Phone Call')], max_length=20, null=True),
        ),
    ]
