# Generated by Django 5.2.6 on 2025-11-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_advisorrequest_age_advisorrequest_dob_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
