# Generated by Django 5.2.6 on 2025-11-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appointment_is_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dream_description',
            new_name='dreams_description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='initial_plan',
            new_name='post_retirement_life_plans',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_savings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dream_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expected_savings_at_retirement',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_retirement_family_together',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_retirement_garage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_retirement_hobbies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_retirement_luxury_life',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_retirement_social_work',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_retirement_travel',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='top_dream_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='top_dream_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='top_dream_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='top_dream_priorities',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_assets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
