# Generated by Django 5.2.6 on 2025-10-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_appointment_communication_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='communication_method',
            field=models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('whatsapp_video_call', 'WhatsApp Video Call'), ('zoom', 'Zoom'), ('phone_call', 'Phone Call')], max_length=20, null=True),
        ),
    ]
