# Generated by Django 5.2.6 on 2025-09-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_advisorrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorrequest',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
