# Generated by Django 5.2.6 on 2025-09-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_advisorrequest_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='advisor_photos/'),
        ),
        migrations.AlterField(
            model_name='advisorrequest',
            name='adhar_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='advisorrequest',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='advisorrequest',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
