# Generated by Django 5.2.6 on 2025-11-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_asset1_profile_asset2_profile_asset3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='asset1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='asset2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='asset3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='asset4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='asset5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_assets',
        ),
    ]
