# Generated by Django 5.2.6 on 2025-09-26 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisorrequest',
            old_name='photo',
            new_name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='advisorrequest',
            name='adhar_number',
        ),
        migrations.RemoveField(
            model_name='advisorrequest',
            name='education',
        ),
        migrations.RemoveField(
            model_name='advisorrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='advisor_type',
            field=models.CharField(blank=True, choices=[('financial', 'Financial Advisor'), ('lifestyle', 'Lifestyle Advisor'), ('legal', 'Legal Advisor'), ('healthcare', 'Healthcare Advisor'), ('travel', 'Travel Advisor'), ('automobile', 'Automobile Advisor'), ('architectural', 'Architectural Advisor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='confirm_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='country_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='educational_certificate',
            field=models.FileField(blank=True, null=True, upload_to='advisor_certificates/'),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='govt_id_file',
            field=models.FileField(blank=True, null=True, upload_to='advisor_ids/'),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='govt_id_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('aadhar', 'Aadhar'), ('license', 'License')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('degree', 'Degree')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='language_preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='previous_companies',
            field=models.TextField(blank=True, help_text='List of companies and roles', null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='advisor_resumes/'),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='specialized_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisorrequest',
            name='state_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advisorrequest',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='advisorrequest',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advisorrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='advisorrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
