# Generated by Django 5.2.6 on 2025-09-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_photo_advisorrequest_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorrequest',
            name='govt_id_proof_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
