# Generated by Django 5.2.6 on 2025-09-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_advisorrequest_govt_id_proof_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Client Profile', 'verbose_name_plural': 'Clients Profiles'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='ClientsProfiles',
        ),
    ]
