# Generated by Django 5.2.6 on 2025-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_appointment_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='decline_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
