import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderFooterWrapper from "@/components/includes/HeaderFooterWrapper";
import RoleVerify from "@/components/includes/RoleVerify";
import { UserProvider } from "@/components/config/UserProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Life Craft",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-bg-cv.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <HeaderFooterWrapper>{children}</HeaderFooterWrapper>
          <RoleVerify />
        </UserProvider>
      </body>
    </html>
  );
}
