# Generated by Django 5.2.6 on 2025-09-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_emailotp_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
